apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: feedback-system

resources:
  - namespace.yaml
  - postgres-cnpg.yaml
  - configmap.yaml
  - deployment.yaml
  - hpa.yaml
  - servicemonitor.yaml
  - ingress.yaml
  - networkpolicy.yaml

images:
  - name: your-registry/feedback-api
    newName: your-registry/feedback-api
    newTag: latest

commonLabels:
  app.kubernetes.io/name: feedback-api
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: feedback-system
