{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gjallarhorn.postgres.name" . }}-secret
  namespace: {{ include "gjallarhorn.namespace" . }}
  labels:
    {{- include "gjallarhorn.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgresql.auth.username | quote }}
  password: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
