apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gjallarhorn.fullname" . }}-secret
  namespace: {{ include "gjallarhorn.namespace" . }}
  labels:
    {{- include "gjallarhorn.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "gjallarhorn.postgres.connectionString" . | quote }}
  KEYCLOAK_URL: {{ include "gjallarhorn.keycloak.url" . | quote }}
  {{- if .Values.webhooks.urls }}
  WEBHOOK_URLS: {{ join "," .Values.webhooks.urls | quote }}
  {{- end }}
  {{- with .Values.app.extraSecretEnv }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
